let produtoEditandoId=null,fotoSelecionada=null,produtosCache=[];
document.addEventListener("DOMContentLoaded",()=>{configurarFoto();carregarProdutos();});
function configurarFoto(){const e=document.getElementById("fotoProduto");if(e)e.addEventListener("change",async t=>{const a=t.target.files[0];fotoSelecionada=a?await arquivoParaBase64(a):null;});}
function arquivoParaBase64(e){return new Promise((t,a)=>{const r=new FileReader;r.onload=()=>t(r.result);r.onerror=a;r.readAsDataURL(e);});}
function mostrarFormulario(){produtoEditandoId=null;document.getElementById("formularioProduto").style.display="block";document.getElementById("tituloFormulario").innerText="Novo produto";limparFormularioProduto();}
function cancelarProduto(){document.getElementById("formularioProduto").style.display="none";produtoEditandoId=null;limparFormularioProduto();}
function limparFormularioProduto(){["nomeProduto","precoProduto","descricaoProduto","fotoProduto","produtoId"].forEach(e=>{const t=document.getElementById(e);if(t)t.value="";});const e=document.getElementById("categoriaProduto");if(e)e.selectedIndex=0;const t=document.getElementById("produtoAtivo");if(t)t.checked=true;document.querySelectorAll(".adicional").forEach(e=>e.checked=false);fotoSelecionada=null;}
function pegarAdicionaisSelecionados(){return [...document.querySelectorAll(".adicional:checked")].map(e=>({nome:e.value,preco:Number(e.dataset.preco||0)}));}
async function salvarProduto(){const e=document.getElementById("nomeProduto").value.trim(),t=document.getElementById("precoProduto").value;if(!e)return alert("Digite o nome do produto.");if(!t||Number(t)<=0)return alert("Digite um preço válido.");if(typeof supabaseClient==="undefined")return alert("A conexão com o Supabase não foi carregada.");const a={nome:e,preco:Number(t),categoria:document.getElementById("categoriaProduto").value,descricao:document.getElementById("descricaoProduto").value.trim(),ativo:document.getElementById("produtoAtivo").checked,adicionais:pegarAdicionaisSelecionados()};if(fotoSelecionada)a.foto=fotoSelecionada;let r;if(produtoEditandoId)r=await supabaseClient.from("produtos").update(a).eq("id",produtoEditandoId);else r=await supabaseClient.from("produtos").insert([a]);if(r.error){console.error(r.error);return alert("Não foi possível salvar: "+r.error.message);}alert(produtoEditandoId?"Produto atualizado com sucesso!":"Produto adicionado com sucesso!");cancelarProduto();carregarProdutos();}
async function carregarProdutos(){const e=document.getElementById("listaProdutos");if(!e||typeof supabaseClient==="undefined")return;e.innerHTML="<p>Carregando produtos...</p>";const{data:t,error:a}=await supabaseClient.from("produtos").select("*").order("id",{ascending:false});if(a){console.error(a);return e.innerHTML="<p>Não foi possível carregar os produtos.</p>";}produtosCache=t||[];if(!produtosCache.length)return e.innerHTML="<p>Nenhum produto cadastrado ainda.</p>";e.innerHTML=produtosCache.map(criarCardProduto).join("");}
function criarCardProduto(e){const t=Number(e.preco||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}),a=e.foto?`<img src="${e.foto}" alt="${escaparHTML(e.nome)}">`:`<div>Sem foto</div>`;return `<article class="produto-admin"><div>${a}</div><div><h3>${escaparHTML(e.nome)}</h3><p>${escaparHTML(e.categoria||"")}</p><p>${escaparHTML(e.descricao||"Sem descrição.")}</p><strong>${t}</strong><p>${e.ativo?"Ativo":"Inativo"}</p><button onclick="editarProduto(${e.id})">Editar</button><button onclick="alternarStatusProduto(${e.id})">${e.ativo?"Inativar":"Ativar"}</button><button onclick="excluirProduto(${e.id})">Excluir</button></div></article>`;}
function escaparHTML(e){return String(e??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}
function editarProduto(e){const t=produtosCache.find(t=>t.id===e);if(!t)return;produtoEditandoId=e;document.getElementById("formularioProduto").style.display="block";document.getElementById("tituloFormulario").innerText="Editar produto";document.getElementById("produtoId").value=t.id;document.getElementById("nomeProduto").value=t.nome||"";document.getElementById("precoProduto").value=t.preco||"";document.getElementById("categoriaProduto").value=t.categoria||"";document.getElementById("descricaoProduto").value=t.descricao||"";document.getElementById("produtoAtivo").checked=t.ativo!==false;fotoSelecionada=t.foto||null;document.querySelectorAll(".adicional").forEach(e=>{e.checked=(Array.isArray(t.adicionais)?t.adicionais:[]).some(t=>(t.nome||t)===e.value);});}
async function alternarStatusProduto(e){const t=produtosCache.find(t=>t.id===e);if(!t)return;const{error:a}=await supabaseClient.from("produtos").update({ativo:!t.ativo}).eq("id",e);if(a)return alert("Não foi possível alterar o status.");carregarProdutos();}
async function excluirProduto(e){const t=produtosCache.find(t=>t.id===e);if(!t||!confirm(`Deseja excluir "${t.nome}"?`))return;const{error:a}=await supabaseClient.from("produtos").delete().eq("id",e);if(a)return alert("Não foi possível excluir o produto.");carregarProdutos();}
