const db = window.supabaseClient;
const CART_KEY = 'elshaddai_carrinho_v2';
let config = {}, products = [], categories = [], cart = [], selectedProduct = null, selectedCategory = '';
const $ = s => document.querySelector(s);
const money = v => Number(v || 0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc = v => String(v ?? '').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const arr = v => Array.isArray(v) ? v : [];
function loadCart(){try{cart=JSON.parse(localStorage.getItem(CART_KEY)||'[]')}catch{cart=[]}}
function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(cart));updateCartBadge()}
function updateCartBadge(){const n=cart.reduce((a,i)=>a+Number(i.quantidade||1),0);document.querySelectorAll('#cartCount,.cart-count').forEach(e=>e.textContent=n)}
function sizes(p){return arr(p?.tamanhos)}
function extras(p){return arr(p?.adicionais)}
function priceLabel(p){const s=sizes(p);return s.length?`A partir de ${money(Math.min(...s.map(x=>Number(x.preco||0))))}`:money(p.preco)}
async function loadStore(){if(!db)return;const r=await db.from('configuracoes_loja').select('*').limit(1).maybeSingle();if(r.error)throw r.error;config=r.data||{};applyStore()}
function applyStore(){const name=config.nome_loja||'Pastelaria El Shaddai', slogan=config.slogan||'Feito a dois, no ponto pra você!', logo=config.logo||'Logo.png';document.querySelectorAll('#storeName,#heroName').forEach(e=>e.textContent=name);document.querySelectorAll('#storeSlogan,#heroSlogan').forEach(e=>e.textContent=slogan);document.querySelectorAll('#storeLogo').forEach(e=>e.src=logo);const open=config.loja_aberta!==false;document.querySelectorAll('#storeStatus,#heroStatus').forEach(e=>{e.textContent=open?'ABERTA':'FECHADA';e.classList.toggle('closed',!open)});const ex=config.configuracoes_extras||{},h=ex.horarios||{};const hours=h.abertura&&h.fechamento?`${h.abertura} às ${h.fechamento}`:(ex.horario_exibicao||'');document.querySelectorAll('#openingHours,#storeHours').forEach(e=>e.textContent=hours?`Horário: ${hours}`:'');const banner=$('#storeBanner');if(banner){if(config.banner){banner.src=config.banner;banner.hidden=false}else banner.hidden=true}const info=$('#shopInfoText');if(info)info.textContent=config.informacoes||'';const ig=$('#instagramLink');if(ig&&config.instagram&&config.instagram_ativo!==false){ig.href=config.instagram;ig.hidden=false}}
async function loadCatalog(){if(!db)return;const [p,c]=await Promise.all([db.from('produtos').select('*').eq('ativo',true).order('id'),db.from('categorias').select('*').eq('ativo',true).order('id')]);if(p.error)throw p.error;if(c.error)throw c.error;products=p.data||[];categories=c.data||[];renderCategories();renderProducts()}
function renderCategories(){const box=$('#categoryChips');if(!box)return;box.innerHTML=`<button class="category-chip active" data-cat="">Todos</button>`+categories.map(c=>`<button class="category-chip" data-cat="${esc(c.nome)}">${esc(c.nome)}</button>`).join('');box.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{selectedCategory=b.dataset.cat;box.querySelectorAll('[data-cat]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts()})}
function renderProducts(){const grid=$('#productsGrid');if(!grid)return;const q=($('#searchInput')?.value||'').toLowerCase().trim();let list=products.filter(p=>(!selectedCategory||p.categoria===selectedCategory)&&(!q||[p.nome,p.categoria,p.descricao,p.ingredientes].some(v=>String(Array.isArray(v)?v.join(' '):v||'').toLowerCase().includes(q))));if(!list.length){grid.innerHTML='<div class="empty-card">Nenhum produto encontrado.</div>';return}const open=config.loja_aberta!==false;grid.innerHTML=list.map(p=>{const disabled=p.disponivel===false||!open;return `<article class="product-card ${disabled?'unavailable':''}">${p.foto?`<img src="${esc(p.foto)}" alt="${esc(p.nome)}">`:''}<div class="product-card-body"><small>${esc(p.categoria||'')}</small><h3>${esc(p.nome)}</h3><p>${esc(p.descricao||'')}</p>${arr(p.ingredientes).length?`<small>Ingredientes: ${esc(arr(p.ingredientes).join(', '))}</small>`:''}<strong>${priceLabel(p)}</strong><button class="primary-btn" ${disabled?'disabled':''} data-add-product="${p.id}">${!open?'Loja fechada':p.disponivel===false?'Indisponível':'Adicionar'}</button></div></article>`}).join('')}
function openProduct(id){selectedProduct=products.find(p=>Number(p.id)===Number(id));if(!selectedProduct)return;const m=$('#productModal');if(!m)return;const s=sizes(selectedProduct),a=extras(selectedProduct);$('#modalPhoto').src=selectedProduct.foto||'';$('#modalPhoto').hidden=!selectedProduct.foto;$('#modalCategory').textContent=selectedProduct.categoria||'';$('#modalName').textContent=selectedProduct.nome;$('#modalDescription').textContent=selectedProduct.descricao||'';$('#modalIngredients').textContent=arr(selectedProduct.ingredientes).length?'Ingredientes: '+arr(selectedProduct.ingredientes).join(', '):'';$('#sizeBox').hidden=!s.length;$('#additionalBox').hidden=!a.length;$('#sizeOptions').innerHTML=s.map((x,i)=>`<label class="choice"><input type="radio" name="sizeChoice" value="${i}" ${i===0?'checked':''}><span>${esc(x.nome||x.tamanho||'Tamanho')} — ${money(x.preco)}</span></label>`).join('');$('#additionalOptions').innerHTML=a.map((x,i)=>`<label class="choice"><input type="checkbox" class="extraChoice" value="${i}"><span>${esc(x.nome||x.titulo||x)}${x.preco?` — +${money(x.preco)}`:''}</span></label>`).join('');$('#qtyValue').textContent='1';$('#productModal').style.display='flex';updateModalPrice()}
function closeProduct(){$('#productModal').style.display='none';selectedProduct=null}
function chosen(){if(!selectedProduct)return{size:null,adds:[],unit:Number(selectedProduct.preco||0)};const s=sizes(selectedProduct),a=extras(selectedProduct);const idx=Number(document.querySelector('input[name="sizeChoice"]:checked')?.value||0),size=s.length?s[idx]:null,adds=[...document.querySelectorAll('.extraChoice:checked')].map(e=>a[Number(e.value)]).filter(Boolean);let unit=Number(size?.preco??selectedProduct.preco??0);adds.forEach(x=>unit+=Number(x.preco||0));return{size,adds,unit}}
function updateModalPrice(){const q=Number($('#qtyValue')?.textContent||1),c=chosen();if($('#modalPrice'))$('#modalPrice').textContent=money(c.unit*q)}
function addSelected(){if(!selectedProduct)return;const c=chosen(),q=Math.max(1,Number($('#qtyValue').textContent||1));const key=JSON.stringify([selectedProduct.id,c.size?.nome||c.size?.tamanho||'',c.adds.map(x=>x.id??x.nome??x)]);const old=cart.find(x=>x._key===key);const names=c.adds.map(x=>x.nome||x.titulo||String(x));if(old){old.quantidade+=q;old.subtotal=old.preco*old.quantidade}else cart.push({_key:key,produto_id:selectedProduct.id,nome:selectedProduct.nome,preco:c.unit,tamanho:c.size?.nome||c.size?.tamanho||'',adicionais:names,quantidade:q,subtotal:c.unit*q});saveCart();closeProduct();toast('Produto adicionado ao pedido')}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>e.classList.remove('show'),2200)}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add-product]');if(add)openProduct(add.dataset.addProduct);if(e.target.matches('[data-close-modal]'))closeProduct();if(e.target.id==='qtyMinus'){const n=Math.max(1,Number($('#qtyValue').textContent)-1);$('#qtyValue').textContent=n;updateModalPrice()}if(e.target.id==='qtyPlus'){const n=Number($('#qtyValue').textContent)+1;$('#qtyValue').textContent=n;updateModalPrice()}if(e.target.closest('input[name="sizeChoice"],.extraChoice'))updateModalPrice()});
function setup(){loadCart();$('#searchInput')?.addEventListener('input',renderProducts);$('#addToCartBtn')?.addEventListener('click',addSelected);document.querySelectorAll('[data-close-modal]').forEach(e=>e.onclick=closeProduct);window.addEventListener('storage',updateCartBadge)}
async function init(){setup();try{await loadStore();await loadCatalog()}catch(e){const m=$('#menuMessage');if(m){m.hidden=false;m.textContent='Não foi possível carregar o cardápio agora.'}console.error(e)}updateCartBadge();setInterval(()=>loadStore().then(renderProducts).catch(()=>{}),30000)}
document.addEventListener('DOMContentLoaded',init);
