const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const CART_KEY="elshaddai_carrinho_v1"; let loja={}, produtos=[], categorias=[], categoriaAtual="__todos__";

function money(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function toast(t){const e=$("#toast");if(!e)return;e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2500)}
function cart(){try{return JSON.parse(localStorage.getItem(CART_KEY)||"[]")}catch{return[]}}
function saveCart(c){localStorage.setItem(CART_KEY,JSON.stringify(c));updateCount()}
function updateCount(){const e=$("#cartCount");if(e)e.textContent=cart().reduce((s,i)=>s+Number(i.q||1),0)}
async function loadLoja(){const {data,error}=await supabaseClient.from("configuracoes_loja").select("*").limit(1).maybeSingle();if(error)throw error;loja=data||{};document.title=loja.nome_loja||"Pastelaria El Shaddai"; if($("#nomeLoja"))$("#nomeLoja").textContent=loja.nome_loja||"Pastelaria El Shaddai";if($("#slogan"))$("#slogan").textContent=loja.slogan||"";if($("#heroInfo"))$("#heroInfo").textContent=loja.informacoes||"";if($("#logo")&&loja.logo)$("#logo").src=loja.logo;if($("#banner")&&loja.banner){$("#banner").src=loja.banner;$("#banner").style.display="block"}if($("#instagramBtn")){const e=$("#instagramBtn");e.style.display=loja.instagram_ativo&&loja.instagram?"inline-block":"none";if(loja.instagram)e.href=loja.instagram}if($("#whatsappBtn")){const e=$("#whatsappBtn");e.style.display=loja.atendimento_ativo&&loja.whatsapp?"inline-block":"none";if(loja.whatsapp)e.href="https://wa.me/"+String(loja.whatsapp).replace(/\D/g,"")}}
async function loadMenu(){const [c,p]=await Promise.all([supabaseClient.from("categorias").select("*").eq("ativo",true).order("id"),supabaseClient.from("produtos").select("*").eq("ativo",true).eq("disponivel",true).order("id")]);if(c.error)throw c.error;if(p.error)throw p.error;categorias=c.data||[];produtos=p.data||[];renderCats();renderProducts()}
function renderCats(){const el=$("#categorias");if(!el)return;el.innerHTML=`<button class="chip ${categoriaAtual==="__todos__"?"active":""}" data-cat="__todos__">Ver todos</button>`+categorias.map(c=>`<button class="chip ${categoriaAtual===c.nome?"active":""}" data-cat="${esc(c.nome)}">${esc(c.nome)}</button>`).join("");$$(".chip").forEach(b=>b.onclick=()=>{categoriaAtual=b.dataset.cat;renderCats();renderProducts()})}
function productPrice(p){const ts=Array.isArray(p.tamanhos)?p.tamanhos:[];return ts.length?Math.min(...ts.map(x=>Number(x.preco||0))):Number(p.preco||0)}
function renderProducts(){const el=$("#produtos");if(!el)return;const q=($("#busca")?.value||"").toLowerCase();let list=produtos.filter(p=>(categoriaAtual==="__todos__"||p.categoria===categoriaAtual)&&`${p.nome} ${p.categoria||""} ${p.descricao||""}`.toLowerCase().includes(q));el.innerHTML=list.map(p=>`<article class="card"><img src="${esc(p.foto||"")}" onerror="this.style.display='none'" alt=""><div class="card-body"><h3>${esc(p.nome)}</h3><div class="muted">${esc(p.descricao||"")}</div><div class="price">${(p.tamanhos||[]).length?"A partir de "+money(productPrice(p)):money(p.preco)}</div><button class="primary" onclick="openProduct(${p.id})">Escolher</button></div></article>`).join("")||`<div class="panel" style="padding:20px">Nenhum produto encontrado.</div>`}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
window.openProduct=id=>{const p=produtos.find(x=>x.id===id);if(!p)return;const ts=Array.isArray(p.tamanhos)?p.tamanhos:[], ads=Array.isArray(p.adicionais)?p.adicionais:[];let html=`<h2>${esc(p.nome)}</h2><p class="muted">${esc(p.descricao||"")}</p>`;if(ts.length)html+=`<h3>Escolha o tamanho</h3><div id="sizes">${ts.map((x,i)=>`<label class="option"><span><input type="radio" name="tam" value="${i}" ${i===0?"checked":""}> ${esc(x.nome)}</span><b>${money(x.preco)}</b></label>`).join("")}</div>`;if(ads.length)html+=`<h3>Adicionais</h3>${ads.map((x,i)=>`<label class="option"><span><input type="checkbox" name="ad" value="${i}"> ${esc(x.nome)}</span><b>+ ${money(x.preco)}</b></label>`).join("")}`;html+=`<label class="field">Quantidade<input id="qty" type="number" min="1" value="1"></label><button class="primary" id="addNow">Adicionar ao carrinho</button>`;$("#modalBody").innerHTML=html;$("#modal").classList.remove("hidden");$("#addNow").onclick=()=>{let size=null;if(ts.length){const i=Number(document.querySelector('input[name="tam"]:checked')?.value);size=ts[i]}const add=ads.filter((_,i)=>document.querySelector(`input[name="ad"][value="${i}"]`)?.checked);const q=Math.max(1,Number($("#qty").value||1));const base=Number(size?.preco??p.preco??0), extra=add.reduce((s,x)=>s+Number(x.preco||0),0);const c=cart();c.push({product_id:p.id,nome:p.nome,preco:base+extra,base_preco:base,tamanho:size?size.nome:null,tamanho_preco:size?Number(size.preco):null,adicionais:add.map(x=>({nome:x.nome,preco:Number(x.preco||0)})),q});saveCart(c);$("#modal").classList.add("hidden");toast("Produto adicionado ao carrinho")}}
if($("#fecharModal"))$("#fecharModal").onclick=()=>$("#modal").classList.add("hidden");
if($("#busca"))$("#busca").oninput=renderProducts;

function initCheckout(){if(!$("#cartArea"))return;renderCheckout();loadLoja().catch(e=>toast("Erro ao carregar configurações"));$("#checkoutArea").addEventListener("submit",submitOrder)}
function renderCheckout(){const c=cart(), area=$("#cartArea");if(!c.length){area.innerHTML=`<section class="panel" style="padding:20px"><h1>Seu carrinho está vazio</h1><a class="primary" href="index.html">Voltar ao cardápio</a></section>`;$("#checkoutArea").innerHTML="";return}let subtotal=c.reduce((s,i)=>s+Number(i.preco)*Number(i.q),0);area.innerHTML=`<section class="panel" style="padding:20px"><h1>Seu carrinho</h1>${c.map((i,n)=>`<div class="line"><span><b>${esc(i.nome)}</b>${i.tamanho?` · ${esc(i.tamanho)}`:""}${i.adicionais?.length?`<small> + ${i.adicionais.map(a=>esc(a.nome)).join(", ")}</small>`:""}<br><small>${i.q} × ${money(i.preco)}</small></span><button class="secondary" onclick="removeCart(${n})">Remover</button></div>`).join("")}<div class="line total"><span>Subtotal</span><span>${money(subtotal)}</span></div></section>`;$("#checkoutArea").innerHTML=`<form id="checkoutForm" class="panel" style="padding:20px"><h2>Finalizar pedido</h2><div class="form-grid"><div class="field"><label>Nome</label><input name="nome" required></div><div class="field"><label>Telefone</label><input name="telefone" required></div></div><div class="field"><label>Recebimento</label><select name="tipo" required><option value="entrega">Entrega</option><option value="retirada">Retirada</option></select></div><div class="field"><label>Endereço</label><input name="endereco" placeholder="Necessário para entrega"></div><div class="field"><label>Observação</label><textarea name="observacao" rows="3"></textarea></div><div class="field"><label>Pagamento</label><select name="pagamento"><option value="pix">Pix</option><option value="cartao">Cartão</option><option value="dinheiro">Dinheiro</option></select></div><div class="field"><label>Troco (se dinheiro)</label><input name="troco" type="number" step="0.01"></div><div class="field"><label>Cupom</label><input name="cupom" placeholder="Opcional"></div><button class="primary" type="submit">Enviar pedido</button><p class="muted">O número do pedido aparecerá após o envio.</p></form>`}
window.removeCart=i=>{const c=cart();c.splice(i,1);saveCart(c);renderCheckout()}
async function submitOrder(ev){ev.preventDefault();const f=new FormData(ev.target),c=cart();if(!c.length)return;const tipo=f.get("tipo");if(tipo==="entrega"&&!String(f.get("endereco")||"").trim()){toast("Informe o endereço para entrega");return}const subtotal=c.reduce((s,i)=>s+Number(i.preco)*Number(i.q),0);let desconto=0,cupom=String(f.get("cupom")||"").trim().toUpperCase();if(cupom){const {data}=await supabaseClient.from("promocoes").select("*").eq("codigo",cupom).eq("ativo",true).maybeSingle();if(data){desconto=Math.min(subtotal,subtotal*Number(data.desconto||0)/100)}}const total=Math.max(0,subtotal-desconto);const itens=c.map(i=>({produto_id:i.product_id,nome:i.nome,quantidade:i.q,tamanho:i.tamanho,tamanho_preco:i.tamanho_preco,adicionais:i.adicionais,preco_unitario:i.preco,subtotal:Number(i.preco)*Number(i.q)}));const payload={cliente_nome:String(f.get("nome")),cliente_telefone:String(f.get("telefone")),endereco:String(f.get("endereco")||""),tipo,pagamento:String(f.get("pagamento")),observacao:`${String(f.get("observacao")||"")}${f.get("troco")?` | Troco para: R$ ${Number(f.get("troco")).toFixed(2)}`:""}${cupom?` | Cupom: ${cupom} | Desconto: ${desconto.toFixed(2)}`:""}`,itens,total,status:"novo"};const {data,error}=await supabaseClient.from("pedidos").insert(payload).select("id").single();if(error){console.error(error);toast("Não foi possível registrar o pedido.");return}const phone=String(loja.whatsapp||"").replace(/\D/g,"");let msg=`PEDIDO #${data.id}\nCliente: ${payload.cliente_nome}\nTelefone: ${payload.cliente_telefone}\nRecebimento: ${tipo}\n${tipo==="entrega"?"Endereço: "+payload.endereco+"\n":""}Itens:\n`;itens.forEach(i=>{msg+=`- ${i.quantidade}x ${i.nome}${i.tamanho?` | Tamanho: ${i.tamanho}`:""}${i.adicionais?.length?` | Adicionais: ${i.adicionais.map(a=>a.nome).join(", ")}`:""} | ${money(i.subtotal)}\n`});msg+=`Subtotal: ${money(subtotal)}\nDesconto: ${money(desconto)}${cupom?` (${cupom})`:""}\nTotal: ${money(total)}\nPagamento: ${payload.pagamento}\nStatus do pagamento: ${payload.pagamento==="pix"?"Aguardando comprovante/confirmação manual":"Aguardando confirmação"}\nObservação: ${f.get("observacao")||"—"}`;saveCart([]);$("#cartArea").innerHTML=`<section class="panel" style="padding:20px"><h1>Pedido registrado!</h1><p>Número do pedido: <b>#${data.id}</b></p><p>Acompanhe em <a href="acompanhar.html?id=${data.id}">acompanhar.html</a>.</p>${phone?`<a class="primary" target="_blank" href="https://wa.me/${phone}?text=${encodeURIComponent(msg)}">Enviar pedido pelo WhatsApp</a>`:""}</section>`;$("#checkoutArea").innerHTML=""}

async function initTrack(){if(!$("#buscarPedido"))return;const id=new URLSearchParams(location.search).get("id");if(id){$("#pedidoId").value=id;findOrder()}$("#buscarPedido").onclick=findOrder}
async function findOrder(){const id=Number($("#pedidoId").value);if(!id)return;const {data,error}=await supabaseClient.from("pedidos").select("*").eq("id",id).maybeSingle();const out=$("#resultado");if(error||!data){out.innerHTML="<p>Pedido não encontrado.</p>";return}const steps=["novo","aceito","em preparo","saiu para entrega","pronto para retirada","entregue","cancelado"];out.innerHTML=`<div class="panel" style="padding:20px;margin-top:15px"><h2>Pedido #${data.id}</h2><p>Status: <span class="status">${esc(data.status)}</span></p><div class="progress">${steps.map(s=>`<div class="step ${s===data.status?"on":""}">${esc(s)}</div>`).join("")}</div><p>Total: <b>${money(data.total)}</b></p></div>`}

updateCount();
if($("#produtos"))(async()=>{try{await loadLoja();await loadMenu()}catch(e){console.error(e);toast("Erro ao carregar o cardápio")}})();
initCheckout();initTrack();
